### ISSUE TITLE
Parse phonewords using findNumbers() function.

### ISSUE THREAD

**Issue by alexglazkov9** [alexglazkov9/phonenumberparser-js#6]
Currently findNumbers() function from util.js can extract numbers of the following format:

*  +1 (111) 111-1111
* (111) 111-1111
* 111.111.1111
* and other fromats that consist of digits and symbols such as (, ), +, -.

Add functionality to parse [phonewords](https://en.wikipedia.org/wiki/Phoneword).

**Comment by jevuu** [comment]
I would like to work on this.
